name: JapaneseChat
version: '1.0.1'
api-version: "1.13"
main: me.syari.jp_chat.Main
authors: [sya_ri, ryoma_1125]
website: https://github.com/ryoma_1125/JapaneseChat
description: "Added '$' to skip conversion. Original by sya_ri."